# config/services.yaml
parameters:
    openrouter.api_key: '%env(OPENROUTER_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # explicitly configure the service with its dependencies
    App\Service\ExternalChatbotService:
        arguments:
            $apiKey: '%openrouter.api_key%'